name: 'Content-Queue Discard'
description: 'Remove issues from your project'
inputs:
  project:
    description: 'Project to act on'
    required: true
  token:
    description: 'GitHub token'
    required: true
  ignoredColumns:
    description: 'Columns to ignore (comma separated)'
    default: 'To Tweet'
runs:
  using: 'node16'
  main: 'index.js'
